site_name: Portfólio — dosciati
site_description: Lista automática de repositórios públicos do GitHub
site_url: https://dosciati.github.io/dosciati/
theme:
  name: material
  language: pt
markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 2-6
nav:
  - Início: index.md
  - Repositórios: repos.md
  - Contato: contato.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dosciati