site_name: Meu Portfólio — GitHub
site_description: Site que lista automaticamente meus repositórios públicos do GitHub
site_url: https://<seu-usuario>.github.io
theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - navigation.footer
    - content.action.edit
markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 2-6
  - admonition
  - def_list
  - tables
nav:
  - Início: index.md
  - Repositórios: repos.md
  - Contato: contato.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dosciati
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andredosciati/